"""
Termux support layer.

Two jobs:

1. Detect whether the bot is running inside Termux (Android).
2. On the very first run in Termux, walk the user through an interactive
   .env setup (asks each value, writes .env next to this file) and then
   loads it into os.environ.

Music / voice-chat streaming is skipped entirely on Termux: pytgcalls +
ntgcalls need native builds that Termux cannot install, so main.py checks
`IS_TERMUX` and never imports pyrogram / pytgcalls there.
"""

import os
import sys

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")


def is_termux() -> bool:
    if os.environ.get("FORCE_TERMUX_MODE", "").strip().lower() in ("1", "true", "yes"):
        return True
    if os.environ.get("TERMUX_VERSION"):
        return True
    prefix = os.environ.get("PREFIX", "")
    if "com.termux" in prefix:
        return True
    return os.path.isdir("/data/data/com.termux/files/usr")


# (env_key, prompt, default, required)
REQUIRED_FIELDS = [
    ("TELEGRAM_API_ID",         "Telegram API ID (my.telegram.org)",            "", True),
    ("TELEGRAM_API_HASH",       "Telegram API HASH",                            "", True),
    ("TELEGRAM_BOT_TOKEN",      "Bot token (@BotFather)",                       "", True),
    ("TELEGRAM_PRIMARY_SESSION","Telethon session string (userbot)",            "", True),
]

OPTIONAL_FIELDS = [
    ("TELEGRAM_OWNER_ID",       "Your numeric user ID",                         "", False),
    ("TELEGRAM_OWNER_USERNAME", "Your username (without @)",                    "", False),
    ("TELEGRAM_LOG_CHANNEL_ID", "Log channel ID (-100...)",                     "", False),
    ("TELEGRAM_HELP_LINK",      "Support link",                                 "", False),
    ("GEMINI_API_KEY",          "Gemini API key (AI features)",                 "", False),
    ("GITHUB_TOKEN",            "GitHub PAT for data backup",                   "", False),
    ("GITHUB_REPO",             "GitHub backup repo (user/repo)",               "", False),
    ("GITHUB_BRANCH",           "GitHub backup branch",                     "main", False),
    ("GITHUB_DATA_PATH",        "GitHub backup file path",     "data/config.json", False),
]


def _ask(prompt: str, default: str, required: bool) -> str:
    while True:
        suffix = f" [{default}]" if default else ("" if required else " [skip]")
        try:
            val = input(f"  {prompt}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n  Setup cancelled.")
            sys.exit(1)
        if not val:
            val = default
        if val or not required:
            return val
        print("  ! Ye field zaroori hai, khaali nahi chhod sakte.")


def run_wizard() -> None:
    print("\n" + "=" * 52)
    print("  TERMUX SETUP — .env file banayi ja rahi hai")
    print("  (music / voice-chat part Termux par disabled rahega)")
    print("=" * 52)

    values = {}
    print("\n-- Required --")
    for key, prompt, default, req in REQUIRED_FIELDS:
        values[key] = _ask(prompt, os.environ.get(key, default), req)

    print("\n-- Optional (Enter dabakar skip karein) --")
    for key, prompt, default, req in OPTIONAL_FIELDS:
        values[key] = _ask(prompt, os.environ.get(key, default), req)

    lines = [
        "# Generated by termux_env.py — Termux run",
        "# Music/voice-chat is disabled in Termux mode.",
        "TERMUX_MODE=1",
        "",
    ]
    for key, _p, _d, _r in REQUIRED_FIELDS + OPTIONAL_FIELDS:
        val = values.get(key, "")
        if val:
            lines.append(f"{key}={val}")
    with open(ENV_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass
    print(f"\n  ✅ Saved: {ENV_PATH}")
    print("  Dobara poochha nahi jayega. Badalna ho to .env edit karein"
          " ya delete karke dobara run karein.\n")


def _load_env_file() -> None:
    try:
        from dotenv import load_dotenv
        load_dotenv(ENV_PATH, override=False)
        return
    except ImportError:
        pass
    if not os.path.isfile(ENV_PATH):
        return
    with open(ENV_PATH, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            os.environ.setdefault(key.strip(), val.strip())


def bootstrap() -> bool:
    """Returns True when running in Termux (music must be skipped)."""
    if not is_termux():
        return False
    if not os.path.isfile(ENV_PATH):
        if sys.stdin is not None and sys.stdin.isatty():
            run_wizard()
        else:
            print("[TERMUX] .env missing — interactive terminal me run karein "
                  "taaki setup wizard chal sake.")
    _load_env_file()
    os.environ["TERMUX_MODE"] = "1"
    os.environ.setdefault("MUSIC_DISABLED", "1")
    return True
